site_name: linax
site_description: The documentation for the linax software package.
site_author: Philippp Nazari, Francesco Maria Ruscio, Benedict Armstrong
repo_url: https://github.com/camail-official/linax
repo_name: camail-official/linax
edit_uri: ""
site_url: https://camail.org/linax/

extra_javascript:
  # The below two make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  - _static/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - _static/custom_css.css

strict: true

markdown_extensions:
  - pymdownx.arithmatex: # Render LaTeX via MathJax
      generic: true
  - pymdownx.superfences # Seems to enable syntax highlighting when used with the Material theme.
  - pymdownx.details # Allowing hidden expandable regions denoted by ???
  - pymdownx.snippets: # Include one Markdown file into another
      base_path: docs
  - admonition
  - toc:
      permalink: "Â¤" # Adds a clickable permalink to each section heading
      toc_depth: 6

theme:
  name: material
  features:
    - navigation.sections # Sections are included in the navigation on the left.
    - toc.integrate # Table of contents is integrated on the left; does not appear separately on the right.
    - header.autohide # header disappears as you scroll
    - content.code.copy
  palette:
    # Light mode / dark mode
    # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
    # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
    - scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github # GitHub logo in top right

plugins:
  - search:
      # See https://github.com/squidfunk/mkdocs-material/discussions/8116#discussioncomment-12632752
      # and https://github.com/patrick-kidger/equinox/issues/984
      # In particular this allows for searching e.g. 'filter_grad' and to match 'equinox.filter_grad'.
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - ipynb
  - hippogriffe:
      show_bases: true
      show_source_links: all

  - mkdocstrings:
      handlers:
        python:
          options:
            force_inspection: true
            heading_level: 4
            inherited_members: true
            members_order: source
            show_bases: false
            show_if_no_docstring: true
            show_overloads: false
            show_root_heading: true
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true

nav:
  - "index.md"
  - Examples:
      - "examples/01_introduction_&_classification.ipynb"
  - API:
      - Base:
          - "api/base/heads.md"
          - "api/base/encoder.md"
          - "api/base/blocks.md"
          - "api/base/sequence_mixer.md"
          - "api/base/channel_mixer.md"
      - Blocks:
          - "api/blocks/standard.md"
      - Models:
          - "api/models/ssm.md"
          - "api/models/linoss.md"
          - "api/models/lru.md"
          - "api/models/s5.md"
      - Sequence Mixers:
          - "api/sequence_mixer/identity.md"
          - "api/sequence_mixer/lru.md"
          - "api/sequence_mixer/s4d.md"
          - "api/sequence_mixer/s5.md"
          - "api/sequence_mixer/linoss.md"
      - Channel Mixers:
          - "api/channel_mixer/identity.md"
          - "api/channel_mixer/mlp.md"
          - "api/channel_mixer/glu.md"
          - "api/channel_mixer/swi_glu.md"
      - Encoders:
          - "api/encoder/embedding.md"
          - "api/encoder/linear.md"
      - Heads:
          - "api/heads/classification.md"
          - "api/heads/regression.md"
  - Contributing:
      - "contributing.md"
