# =============================
# Adapted from:
# 	https://github.com/fla-org/flash-linear-attention
# =============================
name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      # Set up uv
      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.5

      - name: Lint only changed files
        if: ${{ steps.changed-files.outputs.all_changed_files != '' }}
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          uv run pre-commit run --files ${{ steps.changed-files.outputs.all_changed_files }}

      # Optional safety: avoid a silent success if nothing changed
      - name: No files changed
        if: ${{ steps.changed-files.outputs.all_changed_files == '' }}
        run: echo "No changed files to lint."
